# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: enabled
cache: packages


addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'

    packages:
      - libproj-dev
