# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Corner coordinates
#'
#' @param x coordinates
#' @param y coordinates
#' @return character vector of layer names
#'
#' @export
corners_cpp <- function(x, y) {
    .Call(`_quadmesh_corners_cpp`, x, y)
}

